services:
  app:
    build: .
    ports:
      - "80:8080"  # Optional: expose your app's port if needed
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ruben;Username=postgres;Password=password
    depends_on:
      - postgres
    networks:
      - mynetwork
    logging:
      driver: none
  postgres:
    image: postgres
    command: -c shared_buffers=256MB -c max_connections=200
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ruben
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    logging:
      driver: none
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ad.min
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8081:80'
    volumes:
      - pgAdminData:/var/lib/pgadmin
    depends_on:
      - "postgres"
    networks:
      - mynetwork
    logging:
      driver: none

volumes:
  pgdata:
  pgAdminData:

networks:
  mynetwork:
    driver: bridge